import Head from "next/head";
import Link from "next/link";
import Header from "./header";

interface Props {
  children: React.ReactNode;
}

export default function Layout({ children }: Props) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className=" bg-jam-dark-purple">
        <Header />

        <main className="container px-4 mt-12 mx-auto">{children}</main>
      </div>
    </>
  );
}
